# Generated by Django 4.2.4 on 2023-08-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=250, null=True, verbose_name='Заголовок')),
                ('texter', models.TextField(max_length=250, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='header_images/', verbose_name='Измените картинку')),
            ],
            options={
                'verbose_name': 'Окно',
                'verbose_name_plural': 'Блок "Последние проекты"',
            },
        ),
        migrations.CreateModel(
            name='ProjectDerictories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=250, null=True, verbose_name='Заголовок')),
                ('square', models.TextField(blank=True, max_length=250, null=True, verbose_name='Площадь')),
                ('texter', models.TextField(max_length=250, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='header_images/', verbose_name='Измените картинку')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Блок "Каталог Реализованных проектов"',
            },
        ),
    ]
