version: "3.8"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile 
    command: gunicorn djangoProject4.wsgi --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/home/backend
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  nginx:
    image: nginx:mainline-alpine
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./static:/home/backend/static
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

volumes:
  postgres_data:

